name: SkillLevels
main: de.craftlancer.skilllevels.SkillLevels
version: ${project.version}
author: SydMontague
description: Create custom level systems!
softdepend: [CurrencyHandler]
commands:
    level:
        description: Root command for SkillLevels   
        usage: |
            /level help [command] - view a command's help page
            /level stats [player] - shows your or the player's stats
permissions:
    levels.command.help:
        description: Grant access to /level help subcommand
        default: false
    levels.command.stats:
        description: Grant access to /level stats subcommand
        default: false
    levels.command.add:
        description: Grant access to /level add subcommand
        default: false
    levels.command.set:
        description: Grant access to /level set subcommand
        default: false
    levels.command.revoke:
        description: Grant access to /level revoke subcommand
        default: false
    levels.command.reset:
        description: Grant access to /level reset subcommand
        default: false
    levels.command.reload:
        description: Grant access to /level reload subcommand
        default: false
    levels.user:
        default: false
        children:
            levels.command.help: true
            levels.command.stats: true
    levels.admin:
        default: false
        children:
            levels.command.add: true
            levels.command.set: true
            levels.command.revoke: true
            levels.command.reset: true
            levels.command.reload: true
